services:
  mongo-swimmers:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_swimmer_data:/data/db

  mysql-event:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_event_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-race:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_race_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  event-service:
    depends_on:
      - mysql-event
    image: darkcloudhologram/event-service
    ports:
      - 8082:8082
    links:
      - mysql-event
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-event
      MYSQL_DB_PORT: 3307

  swimmer-service:
    depends_on:
      - mongo-swimmers
    image: darkcloudhologram/swimmer-service
    ports:
      - 8081:8081
    links:
      - mongo-swimmers
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-swimmers

  race-service:
    depends_on:
      - event-service
      - swimmer-service
    image: darkcloudhologram/race-service
    ports:
      - 8080:8080
    links:
      - event-service
      - swimmer-service
    environment:
      EVENT_SERVICE_BASEURL: event-service:8082
      SWIMMER_SERVICE_BASEURL: swimmer-service:8081
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-race
      MYSQL_DB_PORT: 3308

volumes:
  mongodb_swimmer_data:
  mysql_event_data:
  mysql_race_data: